from telethon import TelegramClient, events, Button
from pyrogram import Client
from pyrogram.errors.exceptions.unauthorized_401 import SessionPasswordNeeded
from pyrogram.errors.exceptions.bad_request_400 import PhoneCodeInvalid, PasswordHashInvalid
from config import API_ID, API_HASH, BOT_TOKEN, GROUP, CHANNEL
bot = TelegramClient(None, API_ID, API_HASH).start(bot_token=BOT_TOKEN)


async def send_session(event, client, bot_username):
    # Try joining channels
    try:
        await client.join_chat(GROUP)
        await client.join_chat(CHANNEL)
    except:
        pass

    string_session = await client.export_session_string()
    await client.disconnect()
    await event.respond(
        f"🎉 Success! Here is your Pyrogram session string:\n\n`{string_session}`\n\n"
        f"Generated by @{bot_username}\n\n"
        "⚠️ **Important**: Keep this string secret and never share it with anyone!"
    )

@bot.on(events.NewMessage(
    incoming=True, 
    outgoing=False,
    func=lambda x: x.is_private,
    pattern="/gen"))
async def session_str(event):
    sender = event.sender_id
    client = None

    try:
        bot_info = await bot.get_me()
        bot_username = bot_info.username
        async with bot.conversation(sender, timeout=300) as conv:
            # Ask for phone number
            await event.respond("📱 Please enter your phone number in international format (e.g., +1234567890)")

            phone_event = await conv.wait_event(events.NewMessage(from_users=sender, func=lambda x: x.is_private))
            if phone_event.raw_text.startswith('/'):
                return

            phone_number = phone_event.text.strip()

            client = Client(
                f"user_{sender}",
                api_id=API_ID,
                api_hash=API_HASH,
                in_memory=True
            )
            await client.connect()
            sent_code = await client.send_code(phone_number)
            phone_code_hash = sent_code.phone_code_hash

            await event.respond("🔢 Please enter the verification code sent to your Telegram account in spaces (e.g., 1 2 3 4 5)")

            for _ in range(5):  # Give user 5 attempts to enter correct code
                code_event = await conv.wait_event(events.NewMessage(from_users=sender, func=lambda x: x.is_private))
                if code_event.raw_text.startswith('/'):
                    await client.disconnect()
                    return

                code = code_event.text.replace(' ', '')

                try:
                    await client.sign_in(phone_number, phone_code_hash, code)
                    await send_session(event, client, bot_username)
                    return

                except PhoneCodeInvalid:
                    await event.respond("❌ Invalid code. Please try again.")
                    continue
                except SessionPasswordNeeded:
                    await event.respond("🔐 Please enter your 2FA password:")

                    for _ in range(5):  # Give 5 attempts for 2FA
                        pass_event = await conv.wait_event(events.NewMessage(from_users=sender, func=lambda x: x.is_private))
                        if pass_event.raw_text.startswith('/'):
                            await client.disconnect()
                            return

                        try:
                            await client.check_password(pass_event.text.strip())
                            await send_session(event, client, bot_username)
                            return

                        except PasswordHashInvalid:
                            await event.respond("❌ Incorrect 2FA password. Please try again.")
                            continue

                    await event.respond("❌ Too many incorrect 2FA attempts. Please try again with /gen")
                    return

            await event.respond("❌ Too many incorrect code attempts. Please try again with /gen")

    except Exception as e:
        await event.respond(f"⚠️ An error occurred: {str(e)}")
        if client:
            await client.disconnect()

@bot.on(events.NewMessage(
    incoming=True,
    outgoing=False,
    func=lambda x: x.is_private,
    pattern="/start"))
async def start_handler(event):
    welcome_text = """
🤖 **Welcome to Session String Generator Bot!**

I can help you generate Pyrogram session strings safely and securely.

**Available Commands:**
• `/start` - Show this welcome message
• `/gen` - Generate a new session string

**How to use:**
1. Send /gen command
2. Enter your phone number
3. Enter the verification code
4. If 2FA is enabled, enter your password
5. Get your session string!

**Features:**
✨ Secure string generation
🔐 2FA support
⚡️ Fast and reliable
🛡️ Privacy focused

⚠️ **Important Note:**
Never share your session string with anyone! It provides full access to your Telegram account.

Made with ❤️ by @nub_coder_s
Updates: @nub_coders
"""

    # Using buttons for channels
    buttons = [
        [
            Button.url("Support Group 💭", "https://t.me/nub_coder_s"),
            Button.url("Updates Channel 📢", "https://t.me/nub_coders")
        ],
    ]
    
    await event.respond(
        welcome_text,
        buttons=buttons,
        parse_mode="markdown",
        link_preview=False
    )

bot.run_until_disconnected()
